-- Your SQL goes here
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE
  group_accts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    name TEXT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FOREIGN KEY fk_groups_parent_id (parent_id) 
      REFERENCES group_accts (id)
      ON DELETE SET NULL
  );

